version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2

    working_directory: ~/pyMisc

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: code style check
          command: |
            . venv/bin/activate
            pycodestyle -v *.py

      - run:
          name: document style check
          command: |
            . venv/bin/activate
            pydocstyle -v *.py
